# Application Configuration
spring.application.name=residential-complex-multitenant

# Server Configuration
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

# Neon PostgreSQL
#spring.datasource.url=${DB_URL}
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.backendcr=DEBUG


# JWT Configuration
jwt.secret=71985568cb9f27a1b37d5fc2f5d8611f081fd2f91848d01568f896f91a01cb9b
jwt.expiration-ms=3600000